import type { Metadata } from "next";

export const SITE_NAME = "Echo";
export const SITE_TAGLINE = "Words worth coming back to.";
export const SITE_DESCRIPTION =
  "A private library for the quotes that stay with you, and what they meant to you at the time.";

/** The share image generated by `src/app/opengraph-image.tsx`, served at a fixed path. */
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${SITE_NAME}: ${SITE_TAGLINE}`,
};

/**
 * Resolves the public origin that relative metadata URLs (canonical, Open Graph) are built on.
 *
 * @param source - The raw environment to read.
 * @returns AUTH_URL when set, else the Vercel production domain, else localhost.
 */
export function siteUrl(source: Record<string, string | undefined> = process.env): URL {
  if (source.AUTH_URL) return new URL(source.AUTH_URL);
  if (source.VERCEL_PROJECT_PRODUCTION_URL) {
    return new URL(`https://${source.VERCEL_PROJECT_PRODUCTION_URL}`);
  }
  return new URL(`http://localhost:${source.PORT ?? 3000}`);
}

/**
 * Builds the metadata for a public, indexable page: title, description, canonical link and
 * matching Open Graph and Twitter tags.
 *
 * Open Graph and Twitter are restated in full, share image included, because Next.js replaces
 * nested metadata objects rather than merging them with the root layout's or the image file's.
 *
 * @param page - The page's title (omit for the site's own title), description and path.
 * @returns The page's metadata.
 */
export function publicPageMetadata(page: {
  title?: string;
  description: string;
  path: string;
}): Metadata {
  const ogTitle = page.title ? `${page.title} · ${SITE_NAME}` : `${SITE_NAME} · ${SITE_TAGLINE}`;
  return {
    ...(page.title && { title: page.title }),
    description: page.description,
    alternates: { canonical: page.path },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      locale: "en_US",
      url: page.path,
      title: ogTitle,
      description: page.description,
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: ogTitle,
      description: page.description,
      images: [OG_IMAGE],
    },
  };
}
